# Generated by Django 4.0.3 on 2023-02-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('picture', models.FileField(upload_to='Blogs_Images')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.appuser')),
            ],
        ),
    ]
